name: first_firebase_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.5
  dropdown_search: ^5.0.5
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.3
  firebase_storage: ^11.0.6
  google_sign_in: ^5.4.2
  http: ^0.13.5
  image_picker: ^0.8.6
  jiffy: ^5.0.0
  shared_preferences: ^2.0.15
  flutter_facebook_auth: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
flutter:
  uses-material-design: true
