// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAk5ngVjCz-bAI_YN7gUs7Mlb4NoSVpE5k',
    appId: '1:617031189430:web:7e4bec074a8ae0092fb717',
    messagingSenderId: '617031189430',
    projectId: 'mystic-airway-358721',
    authDomain: 'mystic-airway-358721.firebaseapp.com',
    databaseURL:
        'https://mystic-airway-358721-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mystic-airway-358721.appspot.com',
    measurementId: 'G-3SFWT1538P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_JTXt5-Wiza3NgDses2Ohg2hcOjsK6c',
    appId: '1:617031189430:android:9e02e10f37b5d5832fb717',
    messagingSenderId: '617031189430',
    projectId: 'mystic-airway-358721',
    databaseURL:
        'https://mystic-airway-358721-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mystic-airway-358721.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2xcraDzKP7KhvrrWFDuDyqeMjr8Uangg',
    appId: '1:617031189430:ios:659c0fdd227156bd2fb717',
    messagingSenderId: '617031189430',
    projectId: 'mystic-airway-358721',
    databaseURL:
        'https://mystic-airway-358721-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mystic-airway-358721.appspot.com',
    iosClientId:
        '617031189430-4oftc334ppfbaiindh230idrj0svpcat.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2xcraDzKP7KhvrrWFDuDyqeMjr8Uangg',
    appId: '1:617031189430:ios:659c0fdd227156bd2fb717',
    messagingSenderId: '617031189430',
    projectId: 'mystic-airway-358721',
    databaseURL:
        'https://mystic-airway-358721-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mystic-airway-358721.appspot.com',
    iosClientId:
        '617031189430-4oftc334ppfbaiindh230idrj0svpcat.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstFirebaseProject',
  );
}
